/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cms;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFormattedTextField;
import javax.swing.table.TableColumn;
import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.TableModel;

/**
 *
 * @author Mallika
 */
public class IncomeExpenseVoucharEntry extends javax.swing.JInternalFrame {

    private Connection con;
    private PreparedStatement stmt;
    private ResultSet rs;
    private Session session;
    private JComboBox combos[];
    private DefaultTableModel model;

    /**
     * Creates new form IncomeExpenseVoucharEntry
     */
    public IncomeExpenseVoucharEntry(Session session) {

        this.session = session;
        initComponents();

        model = new DefaultTableModel();
        try {
            con = Connector.getConnection();

            String sqlToGetLedgerName = "SELECT ledger_id ,ledger_name from ledger_info where company_id='" + session.getCompanyID() + "' OR company_id=0";
            stmt = con.prepareStatement(sqlToGetLedgerName);
            rs = stmt.executeQuery();
            int rowcount = tableIncomeExpenseVoucharEntry.getRowCount();
            combos = new JComboBox[rowcount];

            while (rs.next()) {
                String ledgerName = rs.getString("ledger_name");
                int ledgerId = rs.getInt("ledger_id");
                LedgerName ledgerNameObject = new LedgerName(ledgerName, ledgerId);

                for (int i = 0; i < rowcount; i++) {
                    if (combos[i] == null) {
                        combos[i] = new JComboBox();
                    }
                    combos[i].addItem(ledgerNameObject);
                    TableColumn col = tableIncomeExpenseVoucharEntry.getColumnModel().getColumn(1);
                    col.setCellEditor(new DefaultCellEditor(combos[i]));
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(JournalEntry.class.getName()).log(Level.SEVERE, null, ex);
        }
        tableIncomeExpenseVoucharEntry.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tableIncomeExpenseVoucharEntry.getColumnModel().getColumn(0).setPreferredWidth(40);
        tableIncomeExpenseVoucharEntry.getColumnModel().getColumn(1).setPreferredWidth(350);
        tableIncomeExpenseVoucharEntry.getColumnModel().getColumn(2).setPreferredWidth(350);
        tableIncomeExpenseVoucharEntry.getColumnModel().getColumn(3).setPreferredWidth(400);

        Action buttonAction = new AbstractAction("Insert") {

            @Override
            public void actionPerformed(ActionEvent evt) {
                String saveIncomeExpenseEntry = "";
                saveIncomeExpenseVoucharEntry(saveIncomeExpenseEntry);

            }
        };

        saveIncomeExpenseVoucharEntry.setAction(buttonAction);

        buttonAction.putValue(Action.MNEMONIC_KEY, KeyEvent.VK_S);

        saveIncomeExpenseVoucharEntry.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(
                KeyStroke.getKeyStroke(KeyEvent.VK_S, KeyEvent.CTRL_DOWN_MASK), saveIncomeExpenseVoucharEntry);

        saveIncomeExpenseVoucharEntry.getActionMap().put(saveIncomeExpenseVoucharEntry, buttonAction);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtVn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        radioIncome = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        radioExpense = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listpaymentMode = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBs = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableIncomeExpenseVoucharEntry = new javax.swing.JTable();
        saveIncomeExpenseVoucharEntry = new javax.swing.JButton();
        jdateAD = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Income Expense Vouchar Entry");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("V.N:");

        txtVn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVnActionPerformed(evt);
            }
        });
        txtVn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVnKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVnKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Income:");

        radioIncome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                radioIncomeKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Expense:");

        radioExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExpenseActionPerformed(evt);
            }
        });
        radioExpense.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                radioExpenseKeyPressed(evt);
            }
        });

        listpaymentMode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listpaymentMode.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cash", "Bank", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listpaymentMode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listpaymentModeKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(listpaymentMode);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Date:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("A.D");

        txtBs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBsActionPerformed(evt);
            }
        });
        txtBs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBsKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("B.S:");

        tableIncomeExpenseVoucharEntry.setAutoCreateRowSorter(true);
        tableIncomeExpenseVoucharEntry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "S.N", "Particular", "Amount", "Naration"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableIncomeExpenseVoucharEntry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableIncomeExpenseVoucharEntryKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tableIncomeExpenseVoucharEntry);

        saveIncomeExpenseVoucharEntry.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveIncomeExpenseVoucharEntry.setText("Save");
        saveIncomeExpenseVoucharEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveIncomeExpenseVoucharEntryActionPerformed(evt);
            }
        });

        jdateAD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        jdateAD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdateADKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jdateAD, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBs, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(16, 16, 16)
                                .addComponent(txtVn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioIncome)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel10))
                                    .addComponent(radioExpense))
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(saveIncomeExpenseVoucharEntry)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(radioIncome)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(radioExpense)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jdateAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(saveIncomeExpenseVoucharEntry)
                .addGap(140, 140, 140))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVnActionPerformed

    private void tableIncomeExpenseVoucharEntryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableIncomeExpenseVoucharEntryKeyPressed


    }//GEN-LAST:event_tableIncomeExpenseVoucharEntryKeyPressed

    private void txtBsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBsActionPerformed
    private int calculate() {
        Vector<Integer> myvector = new Vector();

        TableModel mode = new DefaultTableModel();
        mode = tableIncomeExpenseVoucharEntry.getModel();
        int n = mode.getRowCount();
        for (int i = 0; i < n; i++) {
            if (mode.getValueAt(i, 3) != null) {

                myvector.add((Integer) mode.getValueAt(i, 3));
            }
        }
        return myvector.size();
    }

    private String saveIncomeExpenseVoucharEntry(String saveIncomeExpenseVouchar) {
        String income = "";
        String expense = "";
        if (radioExpense.isSelected()) {
            expense = "expense";
        } else if (radioIncome.isSelected()) {
            income = "income";
        }

        con = Connector.getConnection();
        int numofvalidrows;
        numofvalidrows = calculate();
        if (txtVn.equals("") || jdateAD == null || txtBs.equals("") || numofvalidrows == 0) {
            JOptionPane.showMessageDialog(null, "fill all the information above");

        } else if (numofvalidrows == 0) //if the size of the vector is 0 then the jtable is empty
        {
            JOptionPane.showMessageDialog(null, "You need to add data to the table, because the table is empty");
        } else {
            try {

                String sqlToInsertInIncomeExpenseHeader = "INSERT INTO income_expense_header_field(vno,income,expense,payment_mode,date_Ad,date_Bs,company_id,user_id,financial_year)VALUES(?,?,?,?,?,?,?,?,?)";
                stmt = con.prepareStatement(sqlToInsertInIncomeExpenseHeader, Statement.RETURN_GENERATED_KEYS);
                stmt.setString(1, txtVn.getText());
                stmt.setString(2, income);
                stmt.setString(3, expense);
                stmt.setString(4, listpaymentMode.getSelectedValue());
                String date = jdateAD.getText();
                SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                Date parsed = format.parse(date);
                java.sql.Date sql = new java.sql.Date(parsed.getTime());
                stmt.setDate(5, sql);
                stmt.setString(6, txtBs.getText());
                stmt.setInt(7, session.getCompanyID());
                stmt.setInt(8, session.getUserId());
                stmt.setString(9, session.getFinancialYearFrom());

                stmt.executeUpdate();
                rs = stmt.getGeneratedKeys();
                int incomeExpenseHeaderId = 0;
                while (rs.next()) {
                    incomeExpenseHeaderId = rs.getInt(1);
                }

                int count = tableIncomeExpenseVoucharEntry.getRowCount();
                int col = tableIncomeExpenseVoucharEntry.getColumnCount();
                for (int i = 0; i < count; i++) {
                    LedgerName ledgerName = (LedgerName) combos[i].getSelectedItem();

                    Object sn = i+1;
                    Object particular = tableIncomeExpenseVoucharEntry.getValueAt(i, 1);
                    Object amount = tableIncomeExpenseVoucharEntry.getValueAt(i, 2);
                    Object narration = tableIncomeExpenseVoucharEntry.getValueAt(i, 3);

                    String sqlToInsertIncomeExpenseVoucharEntryTable = "INSERT INTO income_expense_vouchar_entry_table (income_expense_header_id,particular,amount,naration,company_id,user_id,financial_year)VALUES(?,?,?,?,?,?,?)";
                    stmt = con.prepareStatement(sqlToInsertIncomeExpenseVoucharEntryTable);
                    stmt.setInt(1, incomeExpenseHeaderId);
                    stmt.setInt(2, ledgerName.getId());
                    stmt.setObject(3, amount);
                    stmt.setObject(4, narration);
                    stmt.setInt(5, session.getCompanyID());
                    stmt.setInt(6, session.getUserId());
                    stmt.setString(7, session.getFinancialYearFrom());
                    stmt.executeUpdate();

                }

            } catch (SQLException ex) {
                Logger.getLogger(RemitReceiptSendEntry.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(IncomeExpenseVoucharEntry.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return saveIncomeExpenseVouchar;
    }
    private void saveIncomeExpenseVoucharEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveIncomeExpenseVoucharEntryActionPerformed
        String saveIncomeExpenseVoucharEntry = "";
        saveIncomeExpenseVoucharEntry(saveIncomeExpenseVoucharEntry);
    }//GEN-LAST:event_saveIncomeExpenseVoucharEntryActionPerformed

    private void txtVnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVnKeyTyped

        if (txtVn.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_txtVnKeyTyped

    private void radioExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExpenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioExpenseActionPerformed

    private void txtVnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVnKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            radioIncome.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtVnKeyPressed

    private void radioIncomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_radioIncomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            radioExpense.requestFocus();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_radioIncomeKeyPressed

    private void radioExpenseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_radioExpenseKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            listpaymentMode.requestFocus();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_radioExpenseKeyPressed

    private void listpaymentModeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listpaymentModeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jdateAD.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_listpaymentModeKeyPressed

    private void jdateADKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdateADKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtBs.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jdateADKeyPressed

    private void txtBsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBsKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tableIncomeExpenseVoucharEntry.requestFocus();
        }
    }//GEN-LAST:event_txtBsKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField jdateAD;
    private javax.swing.JList<String> listpaymentMode;
    private javax.swing.JRadioButton radioExpense;
    private javax.swing.JRadioButton radioIncome;
    private javax.swing.JButton saveIncomeExpenseVoucharEntry;
    private javax.swing.JTable tableIncomeExpenseVoucharEntry;
    private javax.swing.JTextField txtBs;
    private javax.swing.JTextField txtVn;
    // End of variables declaration//GEN-END:variables
}
