package com.cms;

import java.sql.Connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mallika
 */
public class Welcome extends javax.swing.JFrame {

    private Session session;
    private Connection con = null;

    /*
     * Creates new form welcome
     */
    public Welcome(Session session) {
        con = Connector.getConnection();
        this.session = session;

        initComponents();

    }

    Welcome() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1_ledgerGroup = new javax.swing.JMenuItem();
        jMenuItem2_ledgerUpdate = new javax.swing.JMenuItem();
        jMenuItem3_RemitEntry = new javax.swing.JMenuItem();
        jMenuItem4_loanAmortization = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        voucharEntry = new javax.swing.JMenu();
        IncomeExpenseVoucharEntry = new javax.swing.JMenuItem();
        journalEntry = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        loan = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu8_logout = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1355, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 204));
        jMenuBar1.setAlignmentX(2.0F);
        jMenuBar1.setAlignmentY(3.0F);
        jMenuBar1.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N

        jMenu1.setText("Master");
        jMenu1.setAlignmentX(3.0F);
        jMenu1.setAlignmentY(3.0F);
        jMenu1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jMenuItem1_ledgerGroup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1_ledgerGroup.setText("Ledger Group");
        jMenuItem1_ledgerGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_ledgerGroupActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1_ledgerGroup);

        jMenuItem2_ledgerUpdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2_ledgerUpdate.setText("Ledger Create");
        jMenuItem2_ledgerUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2_ledgerUpdateActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2_ledgerUpdate);

        jMenuItem3_RemitEntry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3_RemitEntry.setText("Remit Entry");
        jMenuItem3_RemitEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3_RemitEntryActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3_RemitEntry);

        jMenuItem4_loanAmortization.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4_loanAmortization.setText("Loan Amortization");
        jMenuItem4_loanAmortization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4_loanAmortizationActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4_loanAmortization);

        jMenuBar1.add(jMenu1);

        jMenu10.setText("Transaction");
        jMenu10.setAlignmentX(3.0F);
        jMenu10.setAlignmentY(3.0F);
        jMenu10.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jMenu10.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Remit Receipt Entry");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem5);

        voucharEntry.setText("Vouchar Entry");
        voucharEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voucharEntryActionPerformed(evt);
            }
        });

        IncomeExpenseVoucharEntry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        IncomeExpenseVoucharEntry.setText("Income/ExpenseVouchar Entry");
        IncomeExpenseVoucharEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncomeExpenseVoucharEntryActionPerformed(evt);
            }
        });
        voucharEntry.add(IncomeExpenseVoucharEntry);

        journalEntry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        journalEntry.setText("Journal Entry");
        journalEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                journalEntryActionPerformed(evt);
            }
        });
        voucharEntry.add(journalEntry);

        jMenu10.add(voucharEntry);

        jMenu2.setText("Bank Entry");

        loan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        loan.setText("Credit and loan");
        loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanActionPerformed(evt);
            }
        });
        jMenu2.add(loan);

        jMenuItem24.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem24.setText("Bank Transaction");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem24);

        jMenu10.add(jMenu2);

        jMenuBar1.add(jMenu10);

        jMenu7.setText("System");
        jMenu7.setAlignmentX(3.0F);
        jMenu7.setAlignmentY(3.0F);
        jMenu7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jMenu7.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("DB Backup");
        jMenu7.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("User Registration");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Company");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuBar1.add(jMenu7);

        jMenu9.setText("Report");
        jMenu9.setAlignmentX(3.0F);
        jMenu9.setAlignmentY(3.0F);
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu9.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jMenuItem2.setText("Day Book");
        jMenu9.add(jMenuItem2);

        jMenu5.setText("Accounts");

        jMenu8.setText("Ledger");

        jMenuItem4.setText("Individual");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem4);

        jMenuItem7.setText("Group Wise");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem7);

        jMenu5.add(jMenu8);

        jMenuItem6.setText("Cash/Bank book");
        jMenu5.add(jMenuItem6);

        jMenuItem10.setText("Remit/Receipt payment");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem11.setText("Income/Expense Vouchar");
        jMenu5.add(jMenuItem11);

        jMenu9.add(jMenu5);

        jMenuItem12.setText("Trial balance");
        jMenu9.add(jMenuItem12);

        jMenuItem13.setText("P/L A/C");
        jMenu9.add(jMenuItem13);

        jMenuItem14.setText("Balance Sheet");
        jMenu9.add(jMenuItem14);

        jMenu11.setText("Cash/Fund Flow");

        jMenuItem15.setText("Cash Flow");
        jMenu11.add(jMenuItem15);

        jMenuItem16.setText("Funds Flow");
        jMenu11.add(jMenuItem16);

        jMenu9.add(jMenu11);

        jMenuBar1.add(jMenu9);

        jMenu6.setText("AR/AP");
        jMenu6.setAlignmentX(3.0F);
        jMenu6.setAlignmentY(3.0F);
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jMenuItem17.setText("LedgerGroup");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem17);

        jMenuItem3.setText("Ledger Info");
        jMenu6.add(jMenuItem3);

        jMenuItem18.setText("Remit");
        jMenu6.add(jMenuItem18);

        jMenuItem19.setText("Remit Receipt Payement");
        jMenu6.add(jMenuItem19);

        jMenuItem20.setText("Income/Expense entry");
        jMenu6.add(jMenuItem20);

        jMenuItem21.setText("Journal Vouchar");
        jMenu6.add(jMenuItem21);

        jMenuItem22.setText("Bank Transaction");
        jMenu6.add(jMenuItem22);

        jMenuBar1.add(jMenu6);

        jMenu8_logout.setText("Logout");
        jMenu8_logout.setAlignmentX(3.0F);
        jMenu8_logout.setAlignmentY(3.0F);
        jMenu8_logout.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jMenu8_logout.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenu8_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8_logoutActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu8_logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1_ledgerGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_ledgerGroupActionPerformed
        con = Connector.getConnection();
        LedgerGroup ledgerGroup = new LedgerGroup(session);
        this.desktopPane.add(ledgerGroup);
        ledgerGroup.show();


    }//GEN-LAST:event_jMenuItem1_ledgerGroupActionPerformed

    private void jMenu8_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8_logoutActionPerformed
        Company company = new Company();
        company.setVisible(true);

    }//GEN-LAST:event_jMenu8_logoutActionPerformed

    private void jMenuItem2_ledgerUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2_ledgerUpdateActionPerformed
        con = Connector.getConnection();
        LedgerCreate ledgerCreateUpdate = new LedgerCreate(session);
        desktopPane.add(ledgerCreateUpdate);
        ledgerCreateUpdate.show();


    }//GEN-LAST:event_jMenuItem2_ledgerUpdateActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        con = Connector.getConnection();
        RemitReceiptSendEntry remitReceiptSendEntry = new RemitReceiptSendEntry(session);
        desktopPane.add(remitReceiptSendEntry);
        remitReceiptSendEntry.show();

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void IncomeExpenseVoucharEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncomeExpenseVoucharEntryActionPerformed
        IncomeExpenseVoucharEntry incomeExpenseVoucharEntry = new IncomeExpenseVoucharEntry(session);
        desktopPane.add(incomeExpenseVoucharEntry);
        incomeExpenseVoucharEntry.show();

    }//GEN-LAST:event_IncomeExpenseVoucharEntryActionPerformed

    private void journalEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_journalEntryActionPerformed
        JournalEntry journalEntry = new JournalEntry(session);
        desktopPane.add(journalEntry);
        journalEntry.show();

    }//GEN-LAST:event_journalEntryActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();// here [this] keyword means your current frame
        //OR simply you can use this.setVisible(false); instead of this.dispose();
        Company company = new Company();
        company.setVisible(true);


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        IndividualLedgerReport individualLedgerReport = new IndividualLedgerReport(session);
        desktopPane.add(individualLedgerReport);
        individualLedgerReport.show();


    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem3_RemitEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3_RemitEntryActionPerformed
        RemitEntry remitEntry = new RemitEntry(session);
        desktopPane.add(remitEntry);
        remitEntry.show();

    }//GEN-LAST:event_jMenuItem3_RemitEntryActionPerformed

    private void jMenuItem4_loanAmortizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4_loanAmortizationActionPerformed
        LoanAmortization loanAmortization = new LoanAmortization(session);
        desktopPane.add(loanAmortization);
        loanAmortization.show();
    }//GEN-LAST:event_jMenuItem4_loanAmortizationActionPerformed

    private void voucharEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voucharEntryActionPerformed
        IncomeExpenseVoucharEntry incomeExpenseVoucharEntry = new IncomeExpenseVoucharEntry(session);
        desktopPane.add(incomeExpenseVoucharEntry);
        incomeExpenseVoucharEntry.show();
    }//GEN-LAST:event_voucharEntryActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        UserRegistration userRegistration = new UserRegistration();
        desktopPane.add(userRegistration);
        userRegistration.show();
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void loanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanActionPerformed
        Loan loan = new Loan(session);
        desktopPane.add(loan);
        loan.show();
    }//GEN-LAST:event_loanActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        BankTransactionEntry bankTransaction = new BankTransactionEntry();
        desktopPane.add(bankTransaction);
        bankTransaction.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        RemitReceiptPaymentReport remitReceiptPaymentReport = new RemitReceiptPaymentReport(session);
        desktopPane.add(remitReceiptPaymentReport);
        remitReceiptPaymentReport.show();    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem IncomeExpenseVoucharEntry;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu8_logout;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem1_ledgerGroup;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem2_ledgerUpdate;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem3_RemitEntry;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem4_loanAmortization;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem journalEntry;
    private javax.swing.JMenuItem loan;
    private javax.swing.JMenu voucharEntry;
    // End of variables declaration//GEN-END:variables

    class textCompany {

        public textCompany() {
        }
    }
}
